main: com.cavetale.merchant.MerchantPlugin
name: Merchant

version: 0.1
api-version: '1.21'

description: Merchants with custom trades
author: StarTux
website: https://github.com/StarTux/Merchant

depend: [Core, Mytems]
softdepend: []

commands:

  merchant:
    aliases: [merchantadmin, merchantadm]
    description: Merchant Command
    permission: merchant.admin
    usage: /merchant

permissions:
  merchant.admin:
    description: Use /merchant
    default: op
